### ISSUE TITLE
Error in running from fresh code pull

### ISSUE THREAD

**Issue by cbondurant** [Scarly-Cat/lamia#3]
**Describe the bug -** Tell us what's broken so we can fix it. Let us know why you consider it broken as well, just so that we understand everything completely:
Attempting to run from a fresh pull of the codebase, following instructions according to the README, leads to an error "Exception in 'lifespan' protocol"

**How did you find it -** Let us know what you did that led you to uncover the bug. Include screenshots where you can:
Ran directly on a fresh pull of the codebase. 

**Browser/operating system versions (and other system information) -** This if information that we need to research this bug:
Python version: `3.7.2`, running in a virtual env
Debian Buster
only python packages installed are the ones in requires.txt

**Anything else -** Share anything that didn't fit into the earlier sections:
Stack trace of the error: 
```python
INFO: Started server process [25429]
INFO: Waiting for application startup.
ERROR: Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/uvicorn/lifespan.py", line 29, in run
    await self.asgi(self.receive, self.send)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/starlette/middleware/lifespan.py", line 65, in __call__
    await self.inner(receiver, send)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/starlette/routing.py", line 483, in __call__
    message = await receive()
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/starlette/middleware/lifespan.py", line 60, in receiver
    await self.startup()
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/starlette/middleware/lifespan.py", line 70, in startup
    await handler()
  File "./lamia/middleware/gino.py", line 114, in startup
    loop=asyncio.get_event_loop(),
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/gino/api.py", line 390, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/gino/strategies.py", line 42, in create
    pool = await dialect.init_pool(u, loop)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 328, in init_pool
    **self._pool_kwargs)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/gino/dialects/asyncpg.py", line 213, in _init
    self._pool = await asyncpg.create_pool(**args)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/asyncpg/pool.py", line 398, in _async__init__
    await self._initialize()
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/asyncpg/pool.py", line 415, in _initialize
    await first_ch.connect()
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/asyncpg/pool.py", line 125, in connect
    self._con = await self._pool._get_new_connection()
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/asyncpg/pool.py", line 461, in _get_new_connection
    **self._connect_kwargs)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/asyncpg/connection.py", line 1688, in connect
    max_cacheable_statement_size=max_cacheable_statement_size)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 551, in _connect
    raise last_error
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 543, in _connect
    connection_class=connection_class)
  File "/home/conner/Documents/git-repos/lamia/venv/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 513, in _connect_addr
    connector, timeout=timeout, loop=loop)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "uvloop/loop.pyx", line 1879, in create_connection
  File "uvloop/loop.pyx", line 1858, in uvloop.loop.Loop.create_connection
ConnectionRefusedError: [Errno 111] Connection refused
ERROR: Application startup failed. Exiting.
```

**Comment by Scarly-Cat** [comment]
I think that this was my error - I created an event loop instead of grabbing the current one. Just patched that over and it *should* work now.
